name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUB_ID}}
      ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Checkout terraform repo
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: SunnyOswal/az-tf
        path: './terraform'

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    # Generates an execution plan for Terraform
    - name: TerraformPlan
      run: |
        varFilePath=$(find ~+ -type f -name '*.json' -print0)
        echo "Var file path: $varFilePath"
        cd terraform
        terraform plan -input=false -var-file=$varFilePath

      # On push to main, build or change infrastructure according to Terraform configuration files
    - name: TerraformApply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      continue-on-error: true
      run: |
        varFilePath=$(find ~+ -type f -name '*.json' -print0)
        cd terraform
        terraform apply -auto-approve -input=false -var-file=$varFilePath

    # If passed, Move var file to processing/passed
    - name: MoveVarFileToPassedDir
      if: steps.TerraformApply.outcome == 'success'
      run: |
        varFilePath=$(find ~+ -type f -name '*.json' -print0)
        mv $varFilePath processing/passed
        git commit -am "File processed succesfully"
        git push -f origin main

    # If failed, Move var file to processing/failed
    - name: MoveVarFileToFailedDir
      if: steps.TerraformApply.outcome != 'success'
      run: |
        varFilePath=$(find ~+ -type f -name '*.json' -print0)
        mv $varFilePath processing/failed
        git commit -am "File processing failed"
        git push -f origin main
